# -*- coding: utf-8 -*-
"""DA_day1_Numpy.ipynb_

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SgREmV4r_9oW1IBWq30zTWnSRPF0bPIr

Arrays
"""

#importing
import numpy as np

#creating 1D array
a=np.array([1,2,3,4])
print(type(a))

#creating a 2D array #rows and columns
B=np.array([[2,3,4],[7,8,9]])
print(B)

#creating a 3D array #rows ,columnsand groups
c=np.array([[[2,3,4],[6,7,8]],[[1,2,3],[1,3,4]]])
print(c)

D=np.ones((3,2))
print(D)

d=np.zeros((3,2))
print(d)

i=np.eye(3)
print(i)

c=np.eye(4,3)
print(i)

R=np.eye(4,3)
print(R)

d=np.ones((2,3,4))
print(d)

#arange
H=np.arange(3,31,3)
print(H)

#reshape
H=np.arange(3,31,3).reshape(5,2)
print(H)

i=np.arange(5,1000,5)
print(i)

v=np.linspace(12,24,10)
print(v)

L=np.arange(1,7).reshape(2,3)
print(L)
R=np.arange(9,15).reshape(2,3)
print(R)

print(L+R)

G=np.sum((L,R))
print(G)

G=np.sum((L,R),axis=0)
print(G)

G=np.sum((L,R),axis=1)
print(G)

print(L*R)

h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=0))

A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A*B)
print(A@B)

b=[25,289,361,81]#find square roots and iterate through result values output:5square is 25...
for i in b:
  print(np.sqrt(i),"square is",i)
print(b)

h=np.ones((4,2))
g=np.ones((4,2))
print(np.sum((h,g),axis=1))

a=np.array([34,35,36,37,38,39])
a.resize(2,3)
b=np.array([4,5,6,7,8,9])
b.resize(2,3)
print(np.vstack((a,b)))#columns
print("\n")
print(np.hstack((a,b)))#rows

a=np.arange(30).reshape(2,3,5)
print(a)